### ISSUE TITLE
v1.0 Adatb alapú rendszerek MILESTONE ISSUE

### ISSUE THREAD

**Issue by molnaredom** [molnaredom/haplmeinda#15]
## Minimális elvárások a dokumentációval kapcsolatban: 
- [x] A dokumentáció számítógéppel készített, szerkesztett dokumentum #10
- [x] A csapaton belül a munka felosztásának részletes leírása #10
- [x] Szöveges, részletes feladatleírás, követelménykatalógus (mi a megvalósítandó cél, milyen
funkciókkal kell rendelkeznie a programnak) #10
- [x] Adatfolyam-diagramok (logikai és fizikai adatfolyam-diagram legalább 1. és 2. szinten) #6 
- [x] Egyedmodell, E-K diagram #12 
- [x] Adatmodellezés és relációs adatelemzés (E-K diagram, E-K diagram leképezése,
normalizálás, adattáblák leírása) #12 
- [x] vagy egyed-esemény mátrix vagy szerep-funkció mátrix * #17
- [x] A megvalósított összetett lekérdezések (lásd: „Minimális elvárások az adatbázissal
kapcsolatban”) leírása: a lekérdezés SQL szintaxisa, helye a programkódban (fájl, sor), a
lekérdezés által megvalósított funkció #10
- [x] A fordításhoz/futtatáshoz szükséges eszközök (használt programnyelv, verzió, külső
függvénykönyvtárak/modulok, ...) #10

## Minimális elvárások az adatbázissal kapcsolatban:
- [x] Összefüggő és konszolidált adattáblák száma legalább 6 darab #8
- [x] Adatrekordok száma az adatbázis egészében logikusan elosztva legalább 120 darab #11
- [x] A feltöltött adatrekordokon be lehessen mutatni a rendszer működését #11
- [x] Összetett lekérdezések száma, amelyek legalább két tábla összekapcsolását, ezen kívül
csoportosítást összesítő függvénnyel, és/vagy alkérdést tartalmaznak: legalább 6 darab #5 
- [x] Integritásellenőrzés #13
- [x] A nem számláló funkciót megvalósító triggerek száma legalább 2 darab #9
- [x] Az alkalmazásban használt, adatbázisban tárolt eljárások és függvények száma legalább 2
darab #16 
## Alkalmazás
- [x] Kényelmes használatot biztosít a felhasználók számára. #2 #3
- Minimális elvárások az alkalmazással kapcsolatban:
  - [x] Az alkalmazásnak rendelkeznie kell adatfelvitelt, -módosítást, -törlést és adatok lekérdezését szolgáló grafikus felhasználói felülettel #14
  - [x] Az alkalmazás funkcionalitását tekintve megfelel a Dokumentációban leírtaknak
